import { StyleSheet } from 'react-native';
import type { ThemeColors } from '../../theme/colors';

/* ==================== Styles ==================== */

export const createSettingsStyles = (colors: ThemeColors) => StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  header: {
    flexDirection: 'row', alignItems: 'center',
    paddingHorizontal: 16, paddingBottom: 14,
  },
  backButton: { width: 40, height: 40, justifyContent: 'center', alignItems: 'center', borderRadius: 8 },
  backIcon: { fontSize: 34, lineHeight: 36, color: colors.text },
  headerTitleBlock: { flex: 1, alignItems: 'center' },
  title: { fontSize: 19, fontWeight: '700', color: colors.text, textAlign: 'center' },
  tabBar: {
    flexGrow: 0,
  },
  tabBarContent: {
    paddingHorizontal: 16, paddingBottom: 12, gap: 8,
  },
  tab: {
    minHeight: 36,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 18,
    backgroundColor: colors.inputBackground,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
  },
  tabActive: { backgroundColor: colors.primaryLight, borderColor: colors.primaryLight },
  tabText: { fontSize: 13, fontWeight: '500', color: colors.textSecondary },
  tabTextActive: { color: colors.primary, fontWeight: '600' },
  switchRow: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    gap: 12,
    backgroundColor: colors.inputBackground,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 10,
  },
  toolCardEnabled: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryLight,
  },
  toolAddPanel: {
    gap: 10,
    backgroundColor: colors.surface,
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 14,
  },
  toolModal: {
    width: '90%',
    maxHeight: '82%',
  },
  toolModalHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 8,
  },
  toolModalDescription: {
    fontSize: 13,
    lineHeight: 19,
    color: colors.textSecondary,
    marginBottom: 10,
  },
  toolModalBody: {
    maxHeight: 480,
  },
  toolModalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: 10,
    marginTop: 12,
  },
  toolNumberRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 14,
  },
  toolNumberField: {
    flex: 1,
    minWidth: 0,
  },
  toolListPreview: {
    gap: 8,
    marginBottom: 12,
  },
  toolListPreviewItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.inputBackground,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  toolListPreviewText: {
    flex: 1,
    minWidth: 0,
  },
  toolListPreviewName: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.text,
  },
  toolListPreviewDescription: {
    marginTop: 4,
    fontSize: 12,
    lineHeight: 17,
    color: colors.textTertiary,
  },
  toolListPreviewStatus: {
    marginTop: 6,
    fontSize: 11,
    fontWeight: '600',
    color: colors.primary,
  },
  mcpResourceSwitches: {
    flexShrink: 0,
    gap: 6,
  },
  mcpResourceSwitchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 6,
  },
  mcpResourceSwitchLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.textTertiary,
  },
  toolDetailText: {
    fontSize: 13,
    lineHeight: 18,
    color: colors.textSecondary,
    marginBottom: 10,
  },
  toolSchemaText: {
    fontSize: 12,
    lineHeight: 18,
    color: colors.text,
    backgroundColor: colors.inputBackground,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 12,
  },
  switchText: {
    flex: 1,
    minWidth: 0,
    paddingRight: 12,
  },
  removeSmallButton: {
    borderWidth: 1, borderColor: colors.danger, borderRadius: 10,
    paddingHorizontal: 12, paddingVertical: 7,
  },
  removeSmallButtonText: { fontSize: 13, fontWeight: '600', color: colors.danger },
  emptyText: { fontSize: 13, color: colors.textTertiary, marginTop: 8 },
  addPathButton: {
    marginTop: 10,
    minHeight: 42,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  addPathButtonText: { fontSize: 14, fontWeight: '600', color: colors.primary },
  dailySourceInlineInput: {
    minHeight: 38,
    marginBottom: 6,
    paddingVertical: 8,
  },
  content: { flex: 1, paddingHorizontal: 20, paddingTop: 8 },
  sectionTitle: {
    fontSize: 12, fontWeight: '700', color: colors.textTertiary,
    marginBottom: 10, marginTop: 10, textTransform: 'uppercase', letterSpacing: 0.5,
  },
  configList: { marginBottom: 16 },
  configChip: {
    paddingHorizontal: 14, paddingVertical: 8, borderRadius: 16, backgroundColor: colors.surface, marginRight: 8,
  },
  configChipActive: { backgroundColor: colors.primary },
  configChipText: { fontSize: 13, fontWeight: '500', color: colors.text },
  configChipTextActive: { color: '#FFFFFF' },
  field: {
    backgroundColor: colors.surface,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 12,
  },
  label: { fontSize: 14, color: colors.primary, marginBottom: 6, fontWeight: '600' },
  input: {
    backgroundColor: colors.background, borderWidth: 1, borderColor: colors.inputBorder,
    borderRadius: 9, padding: 14, fontSize: 14, color: colors.text,
  },
  multilineInput: {
    minHeight: 84,
    textAlignVertical: 'top',
  },
  platformActions: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 10,
  },
  platformActionButton: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 10,
    backgroundColor: colors.surface,
  },
  platformActionText: {
    fontSize: 13,
    color: colors.textSecondary,
    fontWeight: '500',
  },
  platformGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 8,
  },
  platformChip: {
    width: '48%',
    minHeight: 54,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    backgroundColor: colors.inputBackground,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  platformChipSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.surface,
  },
  platformChipLabel: {
    fontSize: 14,
    color: colors.text,
    fontWeight: '600',
  },
  platformChipLabelSelected: {
    color: colors.primary,
  },
  platformChipType: {
    marginTop: 3,
    fontSize: 11,
    color: colors.textTertiary,
  },
  platformChipTypeSelected: {
    color: colors.textSecondary,
  },
  actions: { flexDirection: 'row', gap: 12, marginTop: 8, marginBottom: 32 },
  testButton: {
    flex: 1, paddingVertical: 14, borderRadius: 12,
    borderWidth: 1.5, borderColor: colors.primary,
    backgroundColor: colors.inputBackground,
    justifyContent: 'center', alignItems: 'center',
  },
  testButtonText: { fontSize: 15, fontWeight: '500', color: colors.primary },
  saveButton: {
    flex: 1, paddingVertical: 14, borderRadius: 12, backgroundColor: colors.primary,
    justifyContent: 'center', alignItems: 'center',
  },
  saveButtonText: { fontSize: 15, fontWeight: '500', color: '#FFFFFF' },
  overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.3)', justifyContent: 'center', alignItems: 'center' },
  modal: { backgroundColor: colors.background, borderRadius: 8, borderWidth: 1, borderColor: colors.border, padding: 20, width: '85%', maxHeight: '60%' },
  modalTitle: { fontSize: 17, fontWeight: '600', color: colors.text, marginBottom: 12 },
  largeModal: {
    backgroundColor: colors.background,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 18,
    width: '90%',
    maxHeight: '86%',
  },
  modalBody: {
    flexShrink: 1,
  },
  // Chat settings styles
  hint: { fontSize: 12, color: colors.textTertiary, marginBottom: 12 },
  imageFaceReferenceGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 14,
  },
  imageFaceReferenceItem: {
    width: '48%',
    minWidth: 142,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: 8,
  },
  imageFaceReferenceItemActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryLight,
  },
  imageFaceReferenceImage: {
    width: '100%',
    aspectRatio: 1,
    borderRadius: 10,
    backgroundColor: colors.background,
  },
  imageFaceReferenceMeta: {
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    marginTop: 8,
  },
  imageFaceReferenceLabel: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    fontWeight: '600',
    color: colors.text,
  },
  imageFaceReferenceRemove: {
    minHeight: 32,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: colors.danger,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 6,
  },
  imageFaceReferenceRemoveText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.danger,
  },
  appearanceThemeSaveRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
  },
  appearanceThemeNameInput: {
    flex: 1,
    minWidth: 0,
  },
  appearanceThemeSaveButton: {
    minWidth: 72,
    minHeight: 46,
    borderRadius: 12,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  customStickerPreview: {
    width: 56,
    height: 56,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  customStickerImage: {
    width: '100%',
    height: '100%',
  },
  appearanceClearButton: {
    minHeight: 40,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.danger,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  appearanceClearText: {
    fontSize: 13,
    color: colors.danger,
    fontWeight: '600',
  },
  appearanceThemeToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.surface,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 10,
  },
  appearanceThemeToggleText: {
    flex: 1,
    minWidth: 0,
    paddingRight: 12,
  },
  appearanceThemeHint: {
    fontSize: 12,
    color: colors.textTertiary,
  },
  appearanceThemeToggleAction: {
    fontSize: 13,
    color: colors.primary,
    fontWeight: '600',
  },
  appearanceThemeList: {
    marginBottom: 14,
  },
  appearanceThemeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: colors.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 8,
  },
  appearanceThemeRowActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryLight,
  },
  appearanceThemeName: {
    flex: 1,
    minWidth: 0,
    fontSize: 14,
    color: colors.text,
    fontWeight: '500',
  },
  appearanceThemeNameActive: {
    color: colors.primary,
  },
  appearanceThemeActions: {
    flexDirection: 'row',
    flexShrink: 0,
    gap: 6,
  },
  topBarPreview: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 10,
    marginBottom: 14,
    overflow: 'hidden',
  },
  topBarPreviewBackground: {
    ...StyleSheet.absoluteFill,
    opacity: 0.88,
  },
  topBarPreviewButton: {
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    backgroundColor: colors.background,
  },
  appearanceIconRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: colors.surface,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 10,
  },
  appearanceAssetRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: colors.surface,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 12,
  },
  appearanceIconPreview: {
    width: 42,
    height: 42,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
  },
  appearanceImagePreview: {
    width: 58,
    height: 58,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  floatingBallPreview: {
    width: 58,
    height: 58,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 29,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  welcomeLogoPreview: {
    width: 58,
    height: 58,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  welcomeLogoImage: {
    width: 42,
    height: 42,
  },
  defaultFloatingBallPreview: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: colors.primary,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.78)',
  },
  appearanceImageThumb: {
    width: '100%',
    height: '100%',
  },
  appearanceImagePlaceholder: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textTertiary,
  },
  customInputIconPreview: {
    width: 26,
    height: 26,
  },
  appearanceIconText: {
    flex: 1,
    minWidth: 0,
  },
  appearanceIconActions: {
    flexDirection: 'row',
    gap: 8,
  },
  smallActionButton: {
    minWidth: 48,
    height: 34,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 9,
    borderWidth: 1,
    borderColor: colors.primary,
    backgroundColor: colors.background,
  },
  smallActionButtonDisabled: {
    opacity: 0.45,
  },
  smallActionText: {
    fontSize: 13,
    color: colors.primary,
    fontWeight: '600',
  },
  smallActionTextDisabled: {
    color: colors.textTertiary,
  },
  colorSwatchRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 10,
  },
  colorSwatch: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
  },
  colorSwatchActive: {
    borderWidth: 2,
    borderColor: colors.primary,
  },
  appearanceNumberGrid: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 12,
  },
  appearanceNumberField: {
    flex: 1,
    minWidth: 0,
  },
  segmentedRow: {
    flexDirection: 'row',
    gap: 6,
    backgroundColor: colors.inputBackground,
    borderRadius: 10,
    padding: 5,
    marginBottom: 10,
  },
  segmentedButton: {
    flex: 1,
    minHeight: 40,
    borderRadius: 10,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
  },
  segmentedButtonActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryLight,
  },
  segmentedText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  segmentedTextActive: {
    color: colors.primary,
  },
  importButtonDisabled: {
    opacity: 0.7,
  },
  rangeList: { marginBottom: 12 },
  rangeItem: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    backgroundColor: colors.surface, borderRadius: 10, paddingHorizontal: 14, paddingVertical: 10, marginBottom: 6,
  },
  rangeText: { fontSize: 14, color: colors.text },
  rangeDelete: { fontSize: 14, color: colors.primary, fontWeight: '600', paddingHorizontal: 8 },
  hiddenMessageText: { flex: 1, minWidth: 0, paddingRight: 10 },
  rangeInputRow: {
    flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 6, marginBottom: 20,
  },
  rangeLabel: { fontSize: 14, color: colors.text },
  rangeInput: {
    backgroundColor: colors.inputBackground, borderWidth: 1, borderColor: colors.inputBorder,
    borderRadius: 10, paddingHorizontal: 12, paddingVertical: 8, fontSize: 14, color: colors.text,
    width: 50, textAlign: 'center',
  },
  rangeAddButton: {
    backgroundColor: colors.primary, borderRadius: 10, paddingHorizontal: 14, paddingVertical: 8,
  },
  rangeAddText: { color: '#FFFFFF', fontSize: 14, fontWeight: '500' },
  rangeRestoreButton: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  rangeRestoreText: { color: colors.primary, fontSize: 14, fontWeight: '500' },
  previewBox: {
    backgroundColor: colors.surface, borderRadius: 10, padding: 12, marginBottom: 20,
  },
  previewHint: {
    fontSize: 11, color: colors.textTertiary, marginBottom: 8,
    textTransform: 'uppercase', letterSpacing: 0.5,
  },
  hiddenContextTitle: {
    marginTop: 6,
  },
  previewItem: { gap: 3 },
  previewLabel: { fontSize: 12, color: colors.primary, fontWeight: '600' },
  previewText: { fontSize: 13, color: colors.textSecondary, lineHeight: 18 },
  // Diary styles
  summaryTitleInput: {
    backgroundColor: colors.inputBackground, borderWidth: 1, borderColor: colors.inputBorder,
    borderRadius: 10, padding: 12, fontSize: 15, fontWeight: '500', color: colors.text, marginBottom: 10,
  },
  summaryContentInput: {
    backgroundColor: colors.inputBackground, borderWidth: 1, borderColor: colors.inputBorder,
    borderRadius: 10, padding: 12, fontSize: 14, color: colors.text,
    minHeight: 140, maxHeight: 220, textAlignVertical: 'top', marginBottom: 10,
  },
  diaryModalContentInput: {
    height: 180,
    flexShrink: 1,
  },
  diaryStarText: { fontSize: 20, color: colors.textTertiary },
  diaryStarActive: { color: colors.primary },
  diaryUploadText: { fontSize: 12, color: colors.primary, fontWeight: '500' },
  modalButtons: { flexDirection: 'row', justifyContent: 'flex-end', gap: 12, marginTop: 4 },
  modalCancel: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 8 },
  modalCancelText: { fontSize: 15, color: colors.textSecondary },
  modalConfirm: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 8, backgroundColor: colors.primary },
  modalConfirmText: { fontSize: 15, color: '#FFFFFF', fontWeight: '500' },
});
